FROM ruby:2.6

RUN apt-get update && apt-get install -y build-essential nodejs
# Setting env up
ENV RAILS_ENV='production'
ENV RACK_ENV='production'

# Copy the main application.
COPY . ./
WORKDIR ./

RUN gem install bundler && bundle install --jobs 20 --retry 5
RUN rake db:migrate
RUN bundle exec rake assets:precompile

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
