FROM ruby:2.6

RUN apt-get update && apt-get install -y build-essential nodejs
# Setting env up
ENV RAILS_ENV='production'
ENV RACK_ENV='production'
# Copy the main application.
COPY . ./
WORKDIR ./
ENV ROOT=$pwd

RUN gem install bundler && bundle install --jobs 20 --retry 5
RUN bundle exec rake assets:precompile
EXPOSE 3000
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
