
version: '3'
volumes:
  postgres_data: {}
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - app
    ports:
      - 80:80