FROM ruby:2.6

RUN apt-get update && apt-get install -y build-essential nodejs


# Copy the main application.
COPY . ./
WORKDIR ./
RUN gem install bundler && bundle install --jobs 20 --retry 5

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
